<a href="https://colab.research.google.com/github/Mark4815/TestPublic/blob/main/PluralsightCleaningData.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving hotel_bookings.csv to hotel_bookings.csv

In [ ]:
import pandas as pd
data_df = pd.read_csv('hotel_bookings.csv')
print("The dataset contains", data_df.shape[0], "rows and", data_df.shape[1],"columns")

The dataset contains 119390 rows and 32 columns

In [ ]:
data_df.head(7)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03
5,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03
6,Resort Hotel,0,0,2015,July,27,1,0,2,2,...,No Deposit,NaN,NaN,0,Transient,107.0,0,0,Check-Out,2015-07-03

In [ ]:
pd.set_option("display.max_columns", None)

In [ ]:
data_df.head(7)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,3,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,4,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,C,0,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Corporate,Corporate,0,0,0,A,A,0,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03
5,Resort Hotel,0,14,2015,July,27,1,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03
6,Resort Hotel,0,0,2015,July,27,1,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,0,No Deposit,NaN,NaN,0,Transient,107.0,0,0,Check-Out,2015-07-03

In [ ]:
data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  object
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  object
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  object
 13  country                         118902 non-null  object
 14  market_segment                  119390 non-null  object
 15  distribution_channel            119390 non-null  object
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  object
 20  assigned_room_type              119390 non-null  object
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  object
 23  agent                           103050 non-null  float64
 24  company                         6797 non-null    float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  object
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  object
 31  reservation_status_date         119390 non-null  object
dtypes: float64(4), int64(16), object(12)
memory usage: 29.1+ MB

In [ ]:
data_df.describe()
#Determining different metrics per column. Call out of Adults which is 0, which isn't possible.

,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,agent,company,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests
count,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119386.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,103050.000000,6797.000000,119390.000000,119390.000000,119390.000000,119390.000000
mean,0.370416,104.011416,2016.156554,27.165173,15.798241,0.927599,2.500302,1.856403,0.103890,0.007949,0.031912,0.087118,0.137097,0.221124,86.693382,189.266735,2.321149,101.831122,0.062518,0.571363
std,0.482918,106.863097,0.707476,13.605138,8.780829,0.998613,1.908286,0.579261,0.398561,0.097436,0.175767,0.844336,1.497437,0.652306,110.774548,131.655015,17.594721,50.535790,0.245291,0.792798
min,0.000000,0.000000,2015.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,6.000000,0.000000,-6.380000,0.000000,0.000000
25%,0.000000,18.000000,2016.000000,16.000000,8.000000,0.000000,1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,9.000000,62.000000,0.000000,69.290000,0.000000,0.000000
50%,0.000000,69.000000,2016.000000,28.000000,16.000000,1.000000,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,14.000000,179.000000,0.000000,94.575000,0.000000,0.000000
75%,1.000000,160.000000,2017.000000,38.000000,23.000000,2.000000,3.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,229.000000,270.000000,0.000000,126.000000,0.000000,1.000000
max,1.000000,737.000000,2017.000000,53.000000,31.000000,19.000000,50.000000,55.000000,10.000000,10.000000,1.000000,26.000000,72.000000,21.000000,535.000000,543.000000,391.000000,5400.000000,8.000000,5.000000

In [ ]:
data_df.isnull().sum()/len(data_df)*100
#Determines % of values per column that are null. Possibility to remove columns altogether where this is too high (Company)

hotel                              0.000000
is_canceled                        0.000000
lead_time                          0.000000
arrival_date_year                  0.000000
arrival_date_month                 0.000000
arrival_date_week_number           0.000000
arrival_date_day_of_month          0.000000
stays_in_weekend_nights            0.000000
stays_in_week_nights               0.000000
adults                             0.000000
children                           0.003350
babies                             0.000000
meal                               0.000000
country                            0.408744
market_segment                     0.000000
distribution_channel               0.000000
is_repeated_guest                  0.000000
previous_cancellations             0.000000
previous_bookings_not_canceled     0.000000
reserved_room_type                 0.000000
assigned_room_type                 0.000000
booking_changes                    0.000000
deposit_type                       0.000000
agent                             13.686238
company                           94.306893
days_in_waiting_list               0.000000
customer_type                      0.000000
adr                                0.000000
required_car_parking_spaces        0.000000
total_of_special_requests          0.000000
reservation_status                 0.000000
reservation_status_date            0.000000
dtype: float64

In [ ]:
data_df.drop('Company', inplace=True, axis=1)
#axis = 1 says that we want to remove columns.

In [ ]:
data_df.isnull().sum()
#summing up the amount of null values in each column.

hotel                                  0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               4
babies                                 0
meal                                   0
country                              488
market_segment                         0
distribution_channel                   0
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
deposit_type                           0
agent                              16340
company                           112593
days_in_waiting_list                   0
customer_type                          0
adr                                    0
required_car_parking_spaces            0
total_of_special_requests              0
reservation_status                     0
reservation_status_date                0
dtype: int64

In [ ]:
data_df["children"].value_counts()
#counts the number of instances each value appears in the given column (majority have no children)

children
0.0     110796
1.0       4861
2.0       3652
3.0         76
10.0         1
Name: count, dtype: int64

In [ ]:
data_df["adults"].value_counts()

adults
2     89680
1     23027
3      6202
0       403
4        62
26        5
5         2
27        2
20        2
40        1
55        1
50        1
6         1
10        1
Name: count, dtype: int64

In [ ]:
data_df.sample(10)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
79274,City Hotel,0,3,2016,May,20,12,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,2,A,A,1,No Deposit,NaN,40.0,0,Transient-Party,67.0,1,2,Check-Out,2016-05-13
33169,Resort Hotel,0,44,2017,February,7,15,0,2,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,NaN,0,Transient,85.0,1,0,Check-Out,2017-02-17
68217,City Hotel,1,104,2017,May,20,15,1,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,NaN,NaN,0,Transient,160.0,0,0,Canceled,2017-01-31
114960,City Hotel,0,1,2017,June,26,28,0,1,1,1.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,NaN,0,Transient,136.0,0,0,Check-Out,2017-06-29
107121,City Hotel,0,137,2017,March,10,6,1,1,2,0.0,0,BB,ISR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,37.0,NaN,0,Transient-Party,80.0,0,1,Check-Out,2017-03-08
50378,City Hotel,1,64,2016,April,18,29,1,2,2,0.0,0,BB,LUX,Online TA,TA/TO,0,0,0,A,B,1,No Deposit,9.0,NaN,0,Transient,126.9,0,1,Canceled,2016-04-20
45084,City Hotel,1,102,2015,October,42,16,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,6.0,NaN,0,Transient-Party,101.5,0,0,Canceled,2015-07-06
35876,Resort Hotel,0,134,2017,May,18,3,0,1,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,2,No Deposit,251.0,NaN,0,Transient-Party,62.0,0,1,Check-Out,2017-05-04
79607,City Hotel,0,0,2015,October,44,28,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,NaN,NaN,0,Transient,126.0,0,0,Check-Out,2015-10-30
80777,City Hotel,1,180,2016,April,16,13,0,1,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,21.0,NaN,38,Transient,125.0,0,0,Canceled,2015-11-23

In [ ]:
data_df.duplicated().sum()
#Outputs true if any specific row matches with any other row. By then wrapping a sum() round it, you are counting the number of duplicate rows.

np.int64(31994)

In [ ]:
data_df.drop_duplicates(inplace=True, keep='first')
#this drops all duplicate rows, keeping the first iteration of the row flagged. Same with 'last' if you wanted to keep the last record found instead.

In [ ]:
data_df['reservation_status_date'] = pd.to_datetime(data_df['reservation_status_date'])
#changes the format of the specified column to what you want. In this case, datetime format.

In [ ]:
data_df['reservation_status_year'] = data_df['reservation_status_date'].dt.year
data_df.head()
#this is taking a column and adding a new column with it formatted in a certian way, you can also use month, day, week, dayofweek

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,reservation_status_year
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,3,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01,2015
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,4,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01,2015
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,C,0,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02,2015
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Corporate,Corporate,0,0,0,A,A,0,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02,2015
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03,2015

In [ ]:
cat_cols = [col for col in data_df.columns if data_df[col].dtype=='object']
cat_cols
#this gives you a list comphrehension for the columns where the data type is object.

['hotel',
 'arrival_date_month',
 'meal',
 'country',
 'market_segment',
 'distribution_channel',
 'reserved_room_type',
 'assigned_room_type',
 'deposit_type',
 'customer_type',
 'reservation_status']

In [ ]:
cat_df = data_df[cat_cols]
cat_df.head()
#This takes the above and uses it against the df to create a revised set of data that are just objects.

,hotel,arrival_date_month,meal,country,market_segment,distribution_channel,reserved_room_type,assigned_room_type,deposit_type,customer_type,reservation_status
0,Resort Hotel,July,BB,PRT,Direct,Direct,C,C,No Deposit,Transient,Check-Out
1,Resort Hotel,July,BB,PRT,Direct,Direct,C,C,No Deposit,Transient,Check-Out
2,Resort Hotel,July,BB,GBR,Direct,Direct,A,C,No Deposit,Transient,Check-Out
3,Resort Hotel,July,BB,GBR,Corporate,Corporate,A,A,No Deposit,Transient,Check-Out
4,Resort Hotel,July,BB,GBR,Online TA,TA/TO,A,A,No Deposit,Transient,Check-Out

In [ ]:
cat_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 87396 entries, 0 to 119389
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   hotel                 87396 non-null  object
 1   arrival_date_month    87396 non-null  object
 2   meal                  87396 non-null  object
 3   country               86944 non-null  object
 4   market_segment        87396 non-null  object
 5   distribution_channel  87396 non-null  object
 6   reserved_room_type    87396 non-null  object
 7   assigned_room_type    87396 non-null  object
 8   deposit_type          87396 non-null  object
 9   customer_type         87396 non-null  object
 10  reservation_status    87396 non-null  object
dtypes: object(11)
memory usage: 8.0+ MB

In [ ]:
cat_df.head()

,hotel,arrival_date_month,meal,country,market_segment,distribution_channel,reserved_room_type,assigned_room_type,deposit_type,customer_type,reservation_status
0,Resort Hotel,NaN,BB,PRT,Direct,Direct,C,C,No Deposit,Transient,Check-Out
1,Resort Hotel,NaN,BB,PRT,Direct,Direct,C,C,No Deposit,Transient,Check-Out
2,Resort Hotel,NaN,BB,GBR,Direct,Direct,A,C,No Deposit,Transient,Check-Out
3,Resort Hotel,NaN,BB,GBR,Corporate,Corporate,A,A,No Deposit,Transient,Check-Out
4,Resort Hotel,NaN,BB,GBR,Online TA,TA/TO,A,A,No Deposit,Transient,Check-Out

In [ ]:
data_df["arrival_date_month"].isna().sum()

np.int64(0)

In [ ]:
cat_df['arrival_date_month'] = cat_df['arrival_date_month'].map({'January':1, 'February':2, 'March':3, 'April':4, 'May':5})
cat_df.head(50)

,hotel,arrival_date_month,meal,country,market_segment,distribution_channel,reserved_room_type,assigned_room_type,deposit_type,customer_type,reservation_status
0,Resort Hotel,NaN,BB,PRT,Direct,Direct,C,C,No Deposit,Transient,Check-Out
1,Resort Hotel,NaN,BB,PRT,Direct,Direct,C,C,No Deposit,Transient,Check-Out
2,Resort Hotel,NaN,BB,GBR,Direct,Direct,A,C,No Deposit,Transient,Check-Out
3,Resort Hotel,NaN,BB,GBR,Corporate,Corporate,A,A,No Deposit,Transient,Check-Out
4,Resort Hotel,NaN,BB,GBR,Online TA,TA/TO,A,A,No Deposit,Transient,Check-Out
6,Resort Hotel,NaN,BB,PRT,Direct,Direct,C,C,No Deposit,Transient,Check-Out
7,Resort Hotel,NaN,FB,PRT,Direct,Direct,C,C,No Deposit,Transient,Check-Out
8,Resort Hotel,NaN,BB,PRT,Online TA,TA/TO,A,A,No Deposit,Transient,Canceled
9,Resort Hotel,NaN,HB,PRT,Offline TA/TO,TA/TO,D,D,No Deposit,Transient,Canceled
10,Resort Hotel,NaN,BB,PRT,Online TA,TA/TO,E,E,No Deposit,Transient,Canceled
11,Resort Hotel,NaN,HB,PRT,Online TA,TA/TO,D,D,No Deposit,Transient,Check-Out
12,Resort Hotel,NaN,BB,USA,Online TA,TA/TO,D,E,No Deposit,Transient,Check-Out
13,Resort Hotel,NaN,HB,ESP,Online TA,TA/TO,G,G,No Deposit,Transient,Check-Out
14,Resort Hotel,NaN,BB,PRT,Online TA,TA/TO,E,E,No Deposit,Transient,Check-Out
15,Resort Hotel,NaN,BB,IRL,Online TA,TA/TO,D,E,No Deposit,Transient,Check-Out
16,Resort Hotel,NaN,BB,PRT,Offline TA/TO,TA/TO,E,E,No Deposit,Contract,Check-Out
17,Resort Hotel,NaN,BB,IRL,Online TA,TA/TO,A,E,No Deposit,Transient,Check-Out
18,Resort Hotel,NaN,BB,FRA,Corporate,Corporate,A,G,No Deposit,Transient,Check-Out
19,Resort Hotel,NaN,BB,GBR,Direct,Direct,G,G,No Deposit,Transient,Check-Out
20,Resort Hotel,NaN,BB,GBR,Online TA,TA/TO,F,F,No Deposit,Transient,Check-Out
21,Resort Hotel,NaN,BB,PRT,Direct,Direct,A,A,No Deposit,Transient,Check-Out
23,Resort Hotel,NaN,BB,PRT,Direct,Direct,D,D,No Deposit,Transient,Check-Out
24,Resort Hotel,NaN,HB,GBR,Offline TA/TO,TA/TO,D,I,No Deposit,Contract,Check-Out
25,Resort Hotel,NaN,BB,PRT,Offline TA/TO,TA/TO,D,D,No Deposit,Transient,Check-Out
26,Resort Hotel,NaN,BB,IRL,Offline TA/TO,TA/TO,D,D,No Deposit,Contract,Check-Out
27,Resort Hotel,NaN,BB,PRT,Online TA,TA/TO,E,E,No Deposit,Transient,Canceled
28,Resort Hotel,NaN,BB,PRT,Online TA,TA/TO,A,A,No Deposit,Transient,Check-Out
29,Resort Hotel,NaN,BB,PRT,Online TA,TA/TO,D,D,No Deposit,Transient,Check-Out
30,Resort Hotel,NaN,BB,NaN,Direct,Direct,A,A,No Deposit,Transient,Check-Out
31,Resort Hotel,NaN,BB,GBR,Offline TA/TO,TA/TO,D,D,No Deposit,Transient,Check-Out
32,Resort Hotel,NaN,BB,PRT,Direct,Direct,E,E,No Deposit,Transient,Canceled
33,Resort Hotel,NaN,BB,IRL,Offline TA/TO,TA/TO,A,C,No Deposit,Transient,Check-Out
34,Resort Hotel,NaN,BB,PRT,Online TA,TA/TO,D,D,No Deposit,Transient,Canceled
35,Resort Hotel,NaN,BB,PRT,Online TA,TA/TO,D,D,No Deposit,Transient,Canceled
36,Resort Hotel,NaN,BB,ESP,Online TA,TA/TO,A,C,No Deposit,Transient,Check-Out
37,Resort Hotel,NaN,BB,PRT,Online TA,TA/TO,D,D,No Deposit,Transient,Check-Out
38,Resort Hotel,NaN,BB,PRT,Online TA,TA/TO,D,D,No Deposit,Transient,Canceled
39,Resort Hotel,NaN,HB,ROU,Direct,Direct,E,E,No Deposit,Transient,Check-Out
40,Resort Hotel,NaN,BB,PRT,Online TA,TA/TO,G,G,No Deposit,Transient,Canceled
41,Resort Hotel,NaN,BB,IRL,Offline TA/TO,TA/TO,D,D,No Deposit,Contract,Check-Out
42,Resort Hotel,NaN,BB,ESP,Direct,Direct,F,F,No Deposit,Transient,Check-Out
44,Resort Hotel,NaN,BB,PRT,Online TA,TA/TO,A,A,No Deposit,Transient,Check-Out
45,Resort Hotel,NaN,BB,PRT,Online TA,TA/TO,G,G,No Deposit,Transient,Canceled
46,Resort Hotel,NaN,BB,ESP,Offline TA/TO,TA/TO,A,A,No Deposit,Transient,Check-Out
47,Resort Hotel,NaN,BB,NOR,Offline TA/TO,TA/TO,E,E,No Deposit,Transient-Party,Check-Out
48,Resort Hotel,NaN,HB,GBR,Offline TA/TO,TA/TO,A,B,No Deposit,Contract,Check-Out
49,Resort Hotel,NaN,HB,IRL,Online TA,TA/TO,E,F,No Deposit,Transient,Check-Out
50,Resort Hotel,NaN,BB,NOR,Offline TA/TO,TA/TO,D,D,No Deposit,Transient-Party,Check-Out
51,Resort Hotel,NaN,BB,IRL,Offline TA/TO,TA/TO,A,A,No Deposit,Contract,Check-Out
52,Resort Hotel,NaN,BB,OMN,Offline TA/TO,TA/TO,D,D,No Deposit,Contract,Check-Out